// Find the body element and create new elements to reproduce the HTML page
const body = document.querySelector('body');
const h1 = document.querySelector('h1');
const hr1 = document.createElement('hr');
const h2Task = document.createElement('h2');
const pTask = document.createElement('p');
const ulTask = document.createElement('ul');
const li1 = document.createElement('li');
const li2 = document.createElement('li');
const li3 = document.createElement('li');
const li4 = document.createElement('li');
const li5 = document.createElement('li');
const li6 = document.createElement('li');
const hr2 = document.createElement('hr');
const h2Submission = document.createElement('h2');
const pSubmission = document.createElement('p');
const ulSubmission = document.createElement('ul');
const li7 = document.createElement('li');
const li8 = document.createElement('li');
const li9 = document.createElement('li');
const li10 = document.createElement('li');
const li11 = document.createElement('li');
const li12 = document.createElement('li');
const li13 = document.createElement('li');
const hr3 = document.createElement('hr');

// Change the content and styles of the elements
h1.textContent = 'Lab7 Assignment';
h1.style.color = 'blue';
h2Task.textContent = 'Task';
h2Task.style.color = 'red';
pTask.innerHTML = 'In this task you have to reproduce this HTML page as is using <b>only</b> JavaScript. The task will be evaluated on the basis of the following DOM manipulation techniques:';
//li1.textContent = 'find elements in the DOM (<b>5 points</b>);';
//ul.appendChild(li1);
li1.classList.add('even');
li1.style.color = 'green';
li1.innerHTML ='find elements in the DOM (<b>5 points</b>);';
li2.innerHTML ='create/add/remove elements (<b>5 points</b>);';
li2.classList.add('odd');
li2.style.color = 'purple';
li3.innerHTML = 'change content of the elements (<b>5 points</b>);';
li3.classList.add('even');
li3.style.color = 'green';
li4.innerHTML = 'change styles of the elements (<b>5 points</b>);';
li4.classList.add('odd');
li4.style.color = 'purple';
li5.innerHTML = 'change attributes of the elements (<b>5 points</b>);';
li5.classList.add('even');
li5.style.color = 'green';
li6.innerHTML = 'change classes of the elements (<b>5 points</b>).';
li6.classList.add('odd');
li6.style.color = 'purple';
h2Submission.textContent = 'Submission';
h2Submission.style.color = 'red';
pSubmission.textContent = 'To submit your work, follow these instructions:';
li7.innerHTML = 'Create a new repository on Github, named <b>lab7 (1 point)</b>.';
li7.classList.add('even');
li7.style.color = 'green';
li8.textContent = 'Clone this repository to your local machine and work inside it.';
li8.classList.add('odd');
li8.style.color = 'purple';
li9.innerHTML = 'Create a new HTML file, called <b>index.html</b>, which has only one h1 tag with "Hello, World!" message <b>(1 point)</b>.';
li9.classList.add('even');
li9.style.color = 'green';
li10.innerHTML = 'Create a new JavaScript file, called <b>main.js</b>, which must contain your program (assignment) described above <b>(1 point)</b>.';
li10.classList.add('odd');
li10.style.color = 'purple';
li11.innerHTML = 'Link this <b>main.js</b> file to your <b>index.html</b> file (Note: place your script at the end of the <b>body</b> section).';
li11.classList.add('even');
li11.style.color = 'green';
li12.innerHTML = 'Write a JavaScript program in <b>main.js</b> to make your <b>index.html</b> look identical to this HTML file <b>(5 points)</b>.';
li12.classList.add('odd');
li12.style.color = 'purple';
li13.innerHTML = 'After you finish your work, submit it to the Github <b>(2 points)</b>.';
li13.classList.add('even');
li13.style.color = 'green';

// Append the elements to the body
ulTask.append(li1, li2, li3, li4, li5, li6);
ulSubmission.append(li7, li8, li9, li10, li11, li12, li13);
body.append(h1, hr1, h2Task, pTask, ulTask, hr2, h2Submission, pSubmission, ulSubmission, hr3);